import { useRef, useState } from 'react';
import StatusBadge from './StatusBadge';
import { useDeviation } from '../hooks/useDeviation';
import { DEMO_TEXT } from '../utils/constants';
export default function AiAssistant() {
  const [text, setText] = useState(''); const [question, setQuestion] = useState(''); const input = useRef();
  const { uploadedFile, setUploadedFile, isAnalyzing, analysisResult, missingInformation, confidence, error, analyze, ask, aiMessages } = useDeviation();
  const submit = async () => { if (text.trim() || uploadedFile) await analyze(text, uploadedFile); };
  return <aside className="assistant card"><div className="assistant-header"><div><p className="eyebrow">AI-assisted intake</p><h2>AI Deviation Assistant <StatusBadge tone="beta">BETA</StatusBadge></h2></div><span className="ai-orb">✦</span></div><p className="muted">Upload source evidence or paste an email. The assistant extracts supported facts and suggests an initial assessment.</p>
    <div className="upload-zone" onClick={() => input.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); setUploadedFile(e.dataTransfer.files?.[0]); }}><input ref={input} hidden type="file" accept=".pdf,.docx,.txt,application/pdf,text/plain" onChange={(e) => setUploadedFile(e.target.files?.[0] || null)} /><span className="upload-icon">⇧</span><strong>Drag & drop supporting document here</strong><span>or click to upload · PDF, DOCX, TXT</span>{uploadedFile && <StatusBadge tone="success">{uploadedFile.name}</StatusBadge>}</div>
    <div className="or"><span>OR</span></div><label className="field"><span className="field-label">Paste deviation details / notes</span><textarea rows="7" value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste deviation report, operator notes, or email content…" /></label><button className="sample-link" type="button" onClick={() => setText(DEMO_TEXT)}>Load sample scenario</button>
    <div className="assistant-actions"><button className="button primary" disabled={isAnalyzing || (!text.trim() && !uploadedFile)} onClick={submit}>{isAnalyzing ? 'Analyzing Deviation…' : 'Analyze Deviation'}</button><button className="button secondary" onClick={() => { setText(''); setUploadedFile(null); }} type="button">Clear</button></div>
    {isAnalyzing && <div className="processing"><div className="spinner"/><div><strong>Analyzing deviation…</strong><span>Extracting information · assessing impact · preparing recommendation</span></div></div>}
    {error && <div className="alert error">{error}</div>}
    {analysisResult && <div className="recommendations"><p className="section-heading">AI Recommendation <span className="review-note">Requires human review</span></p><div className="recommendation-grid"><div><span>Suggested Impact</span><b className={`rating ${analysisResult.recommendation.impact?.toLowerCase()}`}>{analysisResult.recommendation.impact || '—'}</b></div><div><span>Suggested Severity</span><b className={`rating ${analysisResult.recommendation.severity?.toLowerCase()}`}>{analysisResult.recommendation.severity || '—'}</b></div></div><div className="reason"><strong>Reasoning</strong><p>{analysisResult.recommendation.reason}</p></div><div className="confidence"><span>Confidence</span><strong>{Math.round((confidence || 0) * 100)}%</strong><div><i style={{ width: `${Math.round((confidence || 0) * 100)}%` }}/></div></div><div className="missing"><strong>Missing Information</strong>{missingInformation.length ? <ul>{missingInformation.map((x) => <li key={x}>{x}</li>)}</ul> : <p>No material gaps identified from the supplied source.</p>}</div></div>}
    <div className="chat"><label className="field"><span className="field-label">Ask about this deviation</span><div className="chat-line"><input value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="e.g. What requires QA review?" onKeyDown={(e) => { if (e.key === 'Enter' && question.trim()) { ask(question); setQuestion(''); } }} /><button type="button" onClick={() => { if (question.trim()) { ask(question); setQuestion(''); } }}>Ask</button></div></label>{aiMessages.slice(-2).map((m, i) => <p className={`message ${m.role}`} key={i}>{m.text}</p>)}</div>
  </aside>;
}
